services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: viala
      POSTGRES_USER: viala
      POSTGRES_PASSWORD: viala
      POSTGRES_INITDB_ARGS: --data-checksums
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U viala -d viala"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/viala
      SPRING_DATASOURCE_USERNAME: viala
      SPRING_DATASOURCE_PASSWORD: viala

volumes:
  postgres_data:
